import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["packages/alfa-*/test/**/*.spec.ts?(x)"],
    exclude: [
      "packages/alfa-angular",
      "packages/alfa-assert",
      "packages/alfa-chai",
      "packages/alfa-cheerio",
      "packages/alfa-cli",
      "packages/alfa-command",
      "packages/alfa-crawler",
      "packages/alfa-cypress",
      "packages/alfa-enzyme",
      "packages/alfa-formatter",
      "packages/alfa-formatter-earl",
      "packages/alfa-formatter-json",
      "packages/alfa-formatter-sarif",
      "packages/alfa-frontier",
      "packages/alfa-interviewer",
      "packages/alfa-jasmine",
      "packages/alfa-jest",
      "packages/alfa-jquery",
      "packages/alfa-playwright",
      "packages/alfa-puppeteer",
      "packages/alfa-react",
      "packages/alfa-scraper",
      "packages/alfa-selenium",
      "packages/alfa-unexpected",
      "packages/alfa-vitest",
      "packages/alfa-vue",
      "packages/alfa-webdriver",
    ],
  },
});
