name: Integrate

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: integrate-${{ github.ref }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # 22 is in Maintenance until April 2027.
        # 24 is Active until October 2026, Maintenance until April 2028.
        # 26 is Current from May 2026 to October 2026, then Active until October 2027, Maintenance until April 2029.
        # 28 will be Current in April/May 2027.
        # https://nodejs.org/en/about/previous-releases
        #
        # There is a problem in v26 + webdriver (see Vitest config file) which has been backported in Node 24.16,
        # so we stay on a working minor for now, rather than disable too many webdriver tests.
        node: [ 22, 24.14, 26 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache:
            yarn
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      - run: >
          yarn config set
          npmScopes.siteimprove.npmAuthToken
          ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install --immutable
      - name: Install Playwright browsers
        # https://playwright.dev/docs/ci-intro
        run: yarn workspace @siteimprove/alfa-playwright playwright install

      - run: yarn dedupe --check
      - run: yarn build --quiet

      - name: Run Vitest based tests
        # We've seen quite a lot of flakyness on tests, most notably hitting a timeout, and incorrect scraping of the
        # immediate redirect pages (alfa-scrape).
        # The timeout is not just something we can increase, since "good" runs finish in a few seconds, and the timeout
        # is at 1 minute. So it feels like this is not just running close to the limit, but something else going on.
        # The alfa-scrape redirect should be investigated at some point.
        # In the meantime, we simply allow the test to run a second time to give it a better chance. This does increase
        # the time-to-error in case of real problems, but these should hopefully be detected locally by devs before
        # creating a PR and running this workflow…
        run: yarn test-main || yarn test-main

      - name: Run other tests
        run: |
          yarn workspace @siteimprove/alfa-cypress run cypress install
          yarn test-other
      - run: yarn validate-structure
      - run: yarn extract --quiet
      - run: yarn knip
