name: PR commands
# Commands that can be run via a comment on the PR.
# Comment `!pr <command-name>` to trigger them.
# See config/pr-commands.json for configuration
# Use `!pr help` for help
#
# See https://github.com/Siteimprove/pr-command

on:
  issue_comment:
    types: [created]

jobs:
  pull-request-command:
    runs-on: ubuntu-latest
    steps:
      - name: "Should pr command run?"
        id: should-run
        uses: siteimprove/pr-command/check-run/check@v2.5
        with:
          # Personal access token (PAT) used to fetch the repository and add reaction on comment.
          token: ${{ secrets.BUILDUSER_GITHUB_WRITE }}

      # The repository has been checked out by PR commands!

      - name: "Set up Node"
        if: env.PR_COMMAND_WILL_RUN == 'true'
        uses: actions/setup-node@v6
        with:
          # We use versions 20 in the integrate workflow
          node-version: 20

      - name: Set up token for Github packages
        if: env.PR_COMMAND_WILL_RUN == 'true'
        run: >
          yarn config set
          npmScopes.siteimprove.npmAuthToken
          ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dependencies"
        if: env.PR_COMMAND_WILL_RUN == 'true'
        run: yarn install --immutable

      - name: Clean secret
        if: env.PR_COMMAND_WILL_RUN == 'true'
        run: git restore .yarnrc.yml

      - name: "React to command"
        uses: siteimprove/pr-command/check-run/run@v2.5
        with:
          # Personal access token (PAT) used to fetch the repository and add reaction on comment.
          token: ${{ secrets.BUILDUSER_GITHUB_WRITE }}
