name: Test

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          registry-url: 'https://npm.pkg.github.com'
          scope: '@siteimprove'
      - name: Configure token for Alfa packages
        run: >
          yarn config set
          npmScopes.siteimprove.npmAuthToken
          ${{ github.token }}

      - name: Print token details
        run: >
          curl -sS -f -I -H "Authorization: token ${{ github.token }}" https://api.github.com

